<<<<<<< HEAD
[server]
headless = true
port = 10000

[browser]
serverAddress = "0.0.0.0"
serverPort = 1000
=======
[server]
headless = true
port = 10000

[browser]
serverAddress = "0.0.0.0"
serverPort = 1000
>>>>>>> 4982c17 (Resolve merge conflicts)
